/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UniaoEstavelRouteImport } from './routes/uniao-estavel'
import { Route as TrabalhistaExecutivoRouteImport } from './routes/trabalhista-executivo'
import { Route as PrevidenciarioRouteImport } from './routes/previdenciario'
import { Route as PensaoEGuardaRouteImport } from './routes/pensao-e-guarda'
import { Route as PensaoRouteImport } from './routes/pensao'
import { Route as LinksRouteImport } from './routes/links'
import { Route as InventarioRouteImport } from './routes/inventario'
import { Route as ImobiliarioRouteImport } from './routes/imobiliario'
import { Route as DivorcioRouteImport } from './routes/divorcio'
import { Route as DireitoDigitalRouteImport } from './routes/direito-digital'
import { Route as DireitoBancarioRouteImport } from './routes/direito-bancario'
import { Route as IndexRouteImport } from './routes/index'

const UniaoEstavelRoute = UniaoEstavelRouteImport.update({
  id: '/uniao-estavel',
  path: '/uniao-estavel',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalhistaExecutivoRoute = TrabalhistaExecutivoRouteImport.update({
  id: '/trabalhista-executivo',
  path: '/trabalhista-executivo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrevidenciarioRoute = PrevidenciarioRouteImport.update({
  id: '/previdenciario',
  path: '/previdenciario',
  getParentRoute: () => rootRouteImport,
} as any)
const PensaoEGuardaRoute = PensaoEGuardaRouteImport.update({
  id: '/pensao-e-guarda',
  path: '/pensao-e-guarda',
  getParentRoute: () => rootRouteImport,
} as any)
const PensaoRoute = PensaoRouteImport.update({
  id: '/pensao',
  path: '/pensao',
  getParentRoute: () => rootRouteImport,
} as any)
const LinksRoute = LinksRouteImport.update({
  id: '/links',
  path: '/links',
  getParentRoute: () => rootRouteImport,
} as any)
const InventarioRoute = InventarioRouteImport.update({
  id: '/inventario',
  path: '/inventario',
  getParentRoute: () => rootRouteImport,
} as any)
const ImobiliarioRoute = ImobiliarioRouteImport.update({
  id: '/imobiliario',
  path: '/imobiliario',
  getParentRoute: () => rootRouteImport,
} as any)
const DivorcioRoute = DivorcioRouteImport.update({
  id: '/divorcio',
  path: '/divorcio',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoDigitalRoute = DireitoDigitalRouteImport.update({
  id: '/direito-digital',
  path: '/direito-digital',
  getParentRoute: () => rootRouteImport,
} as any)
const DireitoBancarioRoute = DireitoBancarioRouteImport.update({
  id: '/direito-bancario',
  path: '/direito-bancario',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/direito-bancario': typeof DireitoBancarioRoute
  '/direito-digital': typeof DireitoDigitalRoute
  '/divorcio': typeof DivorcioRoute
  '/imobiliario': typeof ImobiliarioRoute
  '/inventario': typeof InventarioRoute
  '/links': typeof LinksRoute
  '/pensao': typeof PensaoRoute
  '/pensao-e-guarda': typeof PensaoEGuardaRoute
  '/previdenciario': typeof PrevidenciarioRoute
  '/trabalhista-executivo': typeof TrabalhistaExecutivoRoute
  '/uniao-estavel': typeof UniaoEstavelRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/direito-bancario': typeof DireitoBancarioRoute
  '/direito-digital': typeof DireitoDigitalRoute
  '/divorcio': typeof DivorcioRoute
  '/imobiliario': typeof ImobiliarioRoute
  '/inventario': typeof InventarioRoute
  '/links': typeof LinksRoute
  '/pensao': typeof PensaoRoute
  '/pensao-e-guarda': typeof PensaoEGuardaRoute
  '/previdenciario': typeof PrevidenciarioRoute
  '/trabalhista-executivo': typeof TrabalhistaExecutivoRoute
  '/uniao-estavel': typeof UniaoEstavelRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/direito-bancario': typeof DireitoBancarioRoute
  '/direito-digital': typeof DireitoDigitalRoute
  '/divorcio': typeof DivorcioRoute
  '/imobiliario': typeof ImobiliarioRoute
  '/inventario': typeof InventarioRoute
  '/links': typeof LinksRoute
  '/pensao': typeof PensaoRoute
  '/pensao-e-guarda': typeof PensaoEGuardaRoute
  '/previdenciario': typeof PrevidenciarioRoute
  '/trabalhista-executivo': typeof TrabalhistaExecutivoRoute
  '/uniao-estavel': typeof UniaoEstavelRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/direito-bancario'
    | '/direito-digital'
    | '/divorcio'
    | '/imobiliario'
    | '/inventario'
    | '/links'
    | '/pensao'
    | '/pensao-e-guarda'
    | '/previdenciario'
    | '/trabalhista-executivo'
    | '/uniao-estavel'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/direito-bancario'
    | '/direito-digital'
    | '/divorcio'
    | '/imobiliario'
    | '/inventario'
    | '/links'
    | '/pensao'
    | '/pensao-e-guarda'
    | '/previdenciario'
    | '/trabalhista-executivo'
    | '/uniao-estavel'
  id:
    | '__root__'
    | '/'
    | '/direito-bancario'
    | '/direito-digital'
    | '/divorcio'
    | '/imobiliario'
    | '/inventario'
    | '/links'
    | '/pensao'
    | '/pensao-e-guarda'
    | '/previdenciario'
    | '/trabalhista-executivo'
    | '/uniao-estavel'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DireitoBancarioRoute: typeof DireitoBancarioRoute
  DireitoDigitalRoute: typeof DireitoDigitalRoute
  DivorcioRoute: typeof DivorcioRoute
  ImobiliarioRoute: typeof ImobiliarioRoute
  InventarioRoute: typeof InventarioRoute
  LinksRoute: typeof LinksRoute
  PensaoRoute: typeof PensaoRoute
  PensaoEGuardaRoute: typeof PensaoEGuardaRoute
  PrevidenciarioRoute: typeof PrevidenciarioRoute
  TrabalhistaExecutivoRoute: typeof TrabalhistaExecutivoRoute
  UniaoEstavelRoute: typeof UniaoEstavelRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/uniao-estavel': {
      id: '/uniao-estavel'
      path: '/uniao-estavel'
      fullPath: '/uniao-estavel'
      preLoaderRoute: typeof UniaoEstavelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhista-executivo': {
      id: '/trabalhista-executivo'
      path: '/trabalhista-executivo'
      fullPath: '/trabalhista-executivo'
      preLoaderRoute: typeof TrabalhistaExecutivoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/previdenciario': {
      id: '/previdenciario'
      path: '/previdenciario'
      fullPath: '/previdenciario'
      preLoaderRoute: typeof PrevidenciarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pensao-e-guarda': {
      id: '/pensao-e-guarda'
      path: '/pensao-e-guarda'
      fullPath: '/pensao-e-guarda'
      preLoaderRoute: typeof PensaoEGuardaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pensao': {
      id: '/pensao'
      path: '/pensao'
      fullPath: '/pensao'
      preLoaderRoute: typeof PensaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/links': {
      id: '/links'
      path: '/links'
      fullPath: '/links'
      preLoaderRoute: typeof LinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inventario': {
      id: '/inventario'
      path: '/inventario'
      fullPath: '/inventario'
      preLoaderRoute: typeof InventarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imobiliario': {
      id: '/imobiliario'
      path: '/imobiliario'
      fullPath: '/imobiliario'
      preLoaderRoute: typeof ImobiliarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/divorcio': {
      id: '/divorcio'
      path: '/divorcio'
      fullPath: '/divorcio'
      preLoaderRoute: typeof DivorcioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-digital': {
      id: '/direito-digital'
      path: '/direito-digital'
      fullPath: '/direito-digital'
      preLoaderRoute: typeof DireitoDigitalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/direito-bancario': {
      id: '/direito-bancario'
      path: '/direito-bancario'
      fullPath: '/direito-bancario'
      preLoaderRoute: typeof DireitoBancarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DireitoBancarioRoute: DireitoBancarioRoute,
  DireitoDigitalRoute: DireitoDigitalRoute,
  DivorcioRoute: DivorcioRoute,
  ImobiliarioRoute: ImobiliarioRoute,
  InventarioRoute: InventarioRoute,
  LinksRoute: LinksRoute,
  PensaoRoute: PensaoRoute,
  PensaoEGuardaRoute: PensaoEGuardaRoute,
  PrevidenciarioRoute: PrevidenciarioRoute,
  TrabalhistaExecutivoRoute: TrabalhistaExecutivoRoute,
  UniaoEstavelRoute: UniaoEstavelRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
